# Generated by Django 2.0.3 on 2018-03-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coment',
            new_name='comment',
        ),
    ]
