# Generated by Django 2.0.3 on 2018-03-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBlog', '0002_auto_20180327_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aticle',
            new_name='article',
        ),
    ]
