# Generated by Django 2.0.3 on 2018-03-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBlog', '0003_auto_20180327_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
